### ISSUE TITLE
Moved "docker_ee_url" var to vault

### ISSUE THREAD

**Issue by fsjovatsen** [HewlettPackard/Docker-SimpliVity#6]
The `docker_ee_url` is private and should be moved to `vault`. If this is done one need to add vault in this file.

https://github.com/HewlettPackard/Docker-SimpliVity/blob/f0453f2ca74abc6fcaf227e3ca00945cd8968109/dev/playbooks/install_docker.yml#L22

**Comment by kawai888** [comment]
HI thx for opening up this RFE with us. We will put this on our eng to do list as a future enhancement. Seems to make sense from a security feature. We don't have a date yet on when this will be done as we are in the midst of updating and improving the current Ansible scripts.

**Comment by chris7444** [comment]
this  has been merged in the master branch
