### ISSUE TITLE
Add support for signed cert during ucp installtion

### ISSUE THREAD

**Issue by fsjovatsen** [HewlettPackard/Docker-SimpliVity#7]
It would be nice to have the playbook support installation of ucp with external signed certificates.

https://success.docker.com/article/How_do__I_replace_the_TLS_certificates_for_UCP?

**Comment by kawai888** [comment]
HI thx for opening up this RFE with us. We will put this on our eng to do list as a future enhancement. Seems to make sense from a security feature. We don't have a date yet on when this will be done as we are in the midst of updating and improving the current Ansible scripts.

**Comment by chris7444** [comment]
this has been merged in the master branch
