### ISSUE TITLE
Add support for signed cert during dtr installtion

### ISSUE THREAD

**Issue by fsjovatsen** [HewlettPackard/Docker-SimpliVity#8]
It would be nice to be able to set the following parameters to the dtr installation so that one can use signed cert for both ucp and dtr. 
- ucp-ca
- dtr-ca
- dtr-cert
- dtr-key

See also issue #7

**Comment by kawai888** [comment]
HI thx for opening up this RFE with us.  We will put this on our eng to do list as a future enhancement.  Seems to make sense from a security feature.  We don't have a date yet on when this will be done as we are in the midst of updating and improving the current Ansible scripts.

**Comment by chris7444** [comment]
this has been merged in the master branch
